In [1]:
import pandas as pd
from sqlalchemy import create_engine

### AHA Data

In [2]:
# core + capabilities
keep = [
    'ID',        # hospital_id
    'MNAME',     # name
    'MLOCADDR',  # address
    'MLOCCITY',  # city
    'MSTATE',    # state
    'MLOCZIP',   # zip
    'LAT',       # latitude
    'LONG',      # longitude
    'EMDEPHOS',  # ED present?
    'TRAUMHOS',  # trauma center?
    'TRAUML90',  # trauma level
    'HOSPBD',    # total beds
    'YEAR',      # year 
    # new capability columns:
    'CTSCNHOS',  # CT scanners
    'MSCTHOS',   # multislice CT <64
    'MSCTGHOS',  # multislice CT ≥64
    'MRIHOS',    # MRI units
    'PETCTHOS',  # PET/CT units
    'SPECTHOS',  # SPECT units
    'ULTSNHOS',  # ultrasound units
    'BRNBD',     # burn care beds
    'MSICBD',    # med/surg ICU beds
    'NICBD',     # neonatal ICU beds
    'PEDICBD'    # pediatric ICU beds
]

In [3]:
# Load the CSV file into a pandas DataFrame
aha_df = pd.read_csv('data/raw/albert_aha.csv', usecols=keep, encoding='latin1')

# Only keep year 2023
aha_df = aha_df[aha_df['YEAR'] == 2023]

# Rename columns to best-practice snake_case
aha_df = aha_df.rename(columns={
    'ID':                 'hospital_id',
    'MNAME':              'name',
    'MLOCADDR':           'address',
    'MLOCCITY':           'city',
    'MSTATE':             'state',
    'MLOCZIP':            'zip_code',
    'LAT':                'latitude',
    'LONG':               'longitude',
    'EMDEPHOS':           'has_ed',
    'TRAUMHOS':           'is_trauma_center',
    'TRAUML90':           'trauma_level',
    'HOSPBD':             'total_beds',
    'YEAR':               'year',
    'CTSCNHOS':           'ct_scanners',
    'MSCTHOS':            'ct_multislice_lt64',
    'MSCTGHOS':           'ct_multislice_gte64',
    'MRIHOS':             'mri_units',
    'PETCTHOS':           'pet_ct_units',
    'SPECTHOS':           'spect_units',
    'ULTSNHOS':           'ultrasound_units',
    'BRNBD':              'burn_care_beds',
    'MSICBD':             'icu_med_surg_beds',
    'NICBD':              'icu_neonatal_beds',
    'PEDICBD':            'icu_pediatric_beds'
})

display(aha_df.head())

# display 10 random rows
display(aha_df.sample(10))

print(aha_df.shape)

/var/folders/sb/ybsfm6hs7398knjpcps4h9240000gn/T/ipykernel_37875/3793514954.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  aha_df = pd.read_csv('data/raw/albert_aha.csv', usecols=keep, encoding='latin1')

,hospital_id,name,year,address,city,icu_med_surg_beds,icu_neonatal_beds,icu_pediatric_beds,burn_care_beds,total_beds,...,mri_units,ct_multislice_lt64,ct_multislice_gte64,pet_ct_units,spect_units,ultrasound_units,state,latitude,longitude,zip_code
2,6030010,Kwajalein Hospital,2023,U S Army Kwajalein Atoll,Kwajalein Atoll,NaN,NaN,NaN,NaN,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,MH,8.7167,167.7333,96555
5,6040001,Wilma N. Vazquez Medical Center,2023,"KM 39 1/2 Road 2, Call Box 7001",Vega Baja,0.0,0.0,0.0,0.0,68.0,...,0.0,0.0,0.0,0.0,0.0,0.0,PR,18.4533,-66.4069,00694
8,6040002,Hospital San Francisco,2023,371 Avenida De Diego,San Juan,NaN,NaN,NaN,NaN,133.0,...,NaN,NaN,NaN,NaN,NaN,NaN,PR,18.3986,-66.0389,00923-1711
11,6040004,HIMA San Pablo Caguas,2023,Avenida Munoz Marin,Caguas,NaN,NaN,NaN,NaN,415.0,...,NaN,NaN,NaN,NaN,NaN,NaN,PR,18.2381,-66.0372,00726
14,6040005,Hospital Buen Samaritano,2023,Carr #2 Km 141-1 Ave Severiano Cuevas,Aguadilla,NaN,NaN,NaN,NaN,145.0,...,NaN,NaN,NaN,NaN,NaN,NaN,PR,18.4553,-67.1319,00603

,hospital_id,name,year,address,city,icu_med_surg_beds,icu_neonatal_beds,icu_pediatric_beds,burn_care_beds,total_beds,...,mri_units,ct_multislice_lt64,ct_multislice_gte64,pet_ct_units,spect_units,ultrasound_units,state,latitude,longitude,zip_code
9384,6540464,Oceans Behavioral Hospital of Tupelo,2023,"4579 South Eason Boulevard, Suite B",Tupelo,0.0,0.0,0.0,0.0,34.0,...,0.0,0.0,0.0,0.0,0.0,0.0,MS,34.2226,-88.7746,38801-6539
14891,6743570,CHRISTUS Mother Frances Hospital - Tyler,2023,800 East Dawson Street,Tyler,48.0,29.0,0.0,0.0,495.0,...,1.0,1.0,1.0,0.0,0.0,1.0,TX,32.3429,-95.2921,75701-2036
6516,6430020,Alton Mental Health Center,2023,4500 College Avenue,Alton,NaN,NaN,NaN,NaN,111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,IL,38.9076,-90.1225,62002-5099
325,6110555,MaineGeneral Medical Center,2023,35 Medical Center Parkway,Augusta,8.0,0.0,0.0,0.0,198.0,...,0.0,1.0,1.0,1.0,1.0,1.0,ME,44.3627,-69.7808,04330
12111,6710625,Mercy Hospital Waldron,2023,1341 West 6th Street,Waldron,0.0,0.0,0.0,0.0,24.0,...,0.0,0.0,0.0,0.0,0.0,1.0,AR,34.8965,-94.1057,72958-7642
4508,6381201,Memorial Health Meadows Hospital,2023,1 Meadows Parkway,Vidalia,NaN,NaN,NaN,NaN,57.0,...,NaN,NaN,NaN,NaN,NaN,NaN,GA,32.2090,-82.3759,30474-8759
6028,6420022,Veterans Affairs Northern Indiana Health Care ...,2023,2121 Lake Avenue,Fort Wayne,NaN,NaN,NaN,NaN,217.0,...,NaN,NaN,NaN,NaN,NaN,NaN,IN,41.0912,-85.1099,46805-5100
590,6140460,New England Baptist Hospital,2023,125 Parker Hill Avenue,Boston,5.0,0.0,0.0,0.0,113.0,...,1.0,0.0,1.0,0.0,0.0,1.0,MA,42.3301,-71.1076,02120-2847
2068,6230499,OSS Health,2023,1861 Powder Mill Road,York,NaN,NaN,NaN,NaN,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,PA,39.9169,-76.6956,17402-4723
1587,6220019,Kessler Marlton Rehabilitation,2023,92 Brick Road,Marlton,0.0,0.0,0.0,0.0,61.0,...,0.0,0.0,0.0,0.0,0.0,1.0,NJ,39.8827,-74.9181,08053-2177

(6166, 24)

In [4]:
# get number of row with no NaN values
print(aha_df.isna().sum())

hospital_id               0
name                      0
year                      0
address                   0
city                      0
icu_med_surg_beds      2430
icu_neonatal_beds      2430
icu_pediatric_beds     2430
burn_care_beds         2430
total_beds                0
has_ed                 2430
is_trauma_center       2430
trauma_level           4630
ct_scanners            2430
mri_units              2430
ct_multislice_lt64     2430
ct_multislice_gte64    2430
pet_ct_units           2430
spect_units            2430
ultrasound_units       2430
state                     0
latitude                  0
longitude                 0
zip_code                  0
dtype: int64

In [5]:
print(aha_df.columns)

Index(['hospital_id', 'name', 'year', 'address', 'city', 'icu_med_surg_beds',
       'icu_neonatal_beds', 'icu_pediatric_beds', 'burn_care_beds',
       'total_beds', 'has_ed', 'is_trauma_center', 'trauma_level',
       'ct_scanners', 'mri_units', 'ct_multislice_lt64', 'ct_multislice_gte64',
       'pet_ct_units', 'spect_units', 'ultrasound_units', 'state', 'latitude',
       'longitude', 'zip_code'],
      dtype='object')

In [6]:
# display the rows where city is pasadena
display(aha_df[aha_df['city'] == 'Pasadena'])

,hospital_id,name,year,address,city,icu_med_surg_beds,icu_neonatal_beds,icu_pediatric_beds,burn_care_beds,total_beds,...,mri_units,ct_multislice_lt64,ct_multislice_gte64,pet_ct_units,spect_units,ultrasound_units,state,latitude,longitude,zip_code
13435,6740196,Surgery Specialty Hospitals of America,2023,4301B Vista Road,Pasadena,0.0,0.0,0.0,0.0,10.0,...,1.0,0.0,0.0,0.0,0.0,1.0,TX,29.6591,-95.1779,77504
13735,6740402,St. Luke's Health - Patients Medical Center,2023,4600 East Sam Houston Parkway South,Pasadena,8.0,0.0,0.0,0.0,61.0,...,1.0,1.0,1.0,0.0,0.0,1.0,TX,29.6414,-95.1621,77505-3948
14069,6741002,Oceans Behavioral Hospital of Pasadena,2023,4001 Preston Drive,Pasadena,NaN,NaN,NaN,NaN,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TX,29.6509,-95.1700,77505-2069
14736,6742778,HCA Houston Healthcare Southeast,2023,4000 Spencer Highway,Pasadena,14.0,14.0,0.0,0.0,278.0,...,1.0,1.0,1.0,0.0,1.0,1.0,TX,29.6612,-95.1838,77504-1202
17972,6932350,Huntington Health,2023,100 West California Boulevard,Pasadena,24.0,27.0,0.0,0.0,366.0,...,1.0,1.0,1.0,0.0,1.0,1.0,CA,34.1336,-118.1530,91105-3097
17975,6932360,Las Encinas Hospital,2023,2900 East Del Mar Boulevard,Pasadena,NaN,NaN,NaN,NaN,118.0,...,NaN,NaN,NaN,NaN,NaN,NaN,CA,34.1417,-118.0910,91107-4399

In [8]:
# Generating synthetic data for hospital resource load
import numpy as np

# 1. Ensure reproducibility
np.random.seed(42)

# 2. Specify which bed types to simulate load for
bed_cols = [
    'total_beds',
    'icu_med_surg_beds',
    'icu_neonatal_beds',
    'icu_pediatric_beds',
    'burn_care_beds'
]

# 3. Generate synthetic occupancy data
for col in bed_cols:
    # fill na with 0
    aha_df[col] = aha_df[col].fillna(0)
    # generate random percentage between 20% and 95%
    pct = np.clip(np.random.normal(loc=0.6, scale=0.15, size=len(aha_df)), 0.2, 0.95)
    # Create a new column with the calculated load
    load = (aha_df[col] * pct).round()
    aha_df[f'{col}_load'] = load.astype(int)

In [10]:
# show column where icu_neonatal_beds_load is greater than 0
display(aha_df[aha_df['icu_neonatal_beds_load'] > 0])

,hospital_id,name,year,address,city,icu_med_surg_beds,icu_neonatal_beds,icu_pediatric_beds,burn_care_beds,total_beds,...,ultrasound_units,state,latitude,longitude,zip_code,total_beds_load,icu_med_surg_beds_load,icu_neonatal_beds_load,icu_pediatric_beds_load,burn_care_beds_load
32,6040012,Hospital Menonita Ponce,2023,506 Carr Road,Coto Laurel,9.0,4.0,0.0,0.0,135.0,...,1.0,PR,18.0536,-66.5629,00780,72,5,2,0,0
101,6040250,Hospital De Damas,2023,2213 Ponce Bypass,Ponce,14.0,7.0,0.0,0.0,201.0,...,1.0,PR,17.9970,-66.6180,00717,89,8,2,0,0
119,6040345,Hospital De La Concepcion,2023,"Carr 2, Km 173, Bo Cain Alto",San German,3.0,12.0,0.0,0.0,217.0,...,1.0,PR,18.0926,-67.0404,00683-3920,137,3,7,0,0
235,6110050,Northern Light Eastern Maine Medical Center,2023,489 State Street,Bangor,26.0,29.0,6.0,0.0,361.0,...,1.0,ME,44.8074,-68.7526,04401-6674,222,13,24,3,0
373,6120170,Dartmouth-Hitchcock Medical Center,2023,1 Medical Center Drive,Lebanon,38.0,30.0,8.0,0.0,438.0,...,1.0,NH,43.6760,-72.2730,03756-1000,301,21,22,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18407,6940010,Alaska Native Medical Center,2023,4315 Diplomacy Drive,Anchorage,18.0,12.0,0.0,0.0,189.0,...,0.0,AK,61.1827,-149.8010,99508-5926,84,10,8,0,0
18413,6940020,Providence Alaska Medical Center,2023,3200 Providence Drive,Anchorage,28.0,66.0,9.0,0.0,401.0,...,1.0,AK,61.1884,-149.8190,99508-4615,190,20,32,4,0
18428,6940058,Fairbanks Memorial Hospital,2023,1650 Cowles Street,Fairbanks,7.0,7.0,0.0,0.0,217.0,...,1.0,AK,64.8312,-147.7400,99701-5998,105,4,4,0,0
18524,6950330,Kaiser Permanente Medical Center,2023,3288 Moanalua Road,Honolulu,15.0,20.0,2.0,0.0,215.0,...,1.0,HI,21.3633,-157.9000,96819-1469,152,10,6,1,0
18527,6950335,Kapiolani Medical Center for Women & Children,2023,1319 Punahou Street,Honolulu,9.0,74.0,14.0,0.0,253.0,...,1.0,HI,21.3001,-157.8340,96826-1001,169,7,55,9,0

In [ ]:
# push to MySQL
engine = create_engine("mysql+pymysql://root:pass@localhost:3306/hospitals")
aha_df.to_sql('AHA_Hospitals', engine, if_exists='replace', index=False)